version: "3.9"

services:
  traefik:
    image: traefik:v3.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 8085
        published: 8085
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/traefik/dev/static.yml:/etc/traefik/traefik.yml:ro
      - ./deploy/traefik/dev/dynamic.yml:/etc/traefik/dynamic.yml:ro
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

  backend:
    image: kracker-backend:local
    env_file:
      - back/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

  frontend:
    image: kracker-frontend:local
    env_file:
      - front/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

networks:
  kracker:
    driver: bridge
