version: "3.9"

services:
  traefik:
    image: traefik:v3.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"

  backend:
    image: kracker-backend:local
    env_file:
      - back/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

  frontend:
    image: kracker-frontend:local
    env_file:
      - front/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

networks:
  kracker:
    driver: bridge
