version: "3.9"

services:
  traefik:
    image: traefik:v3.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker
    command:
      - "--log.level=DEBUG"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"

  backend:
    image: kracker-backend:local
    env_file:
      - back/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/back`)"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/back"
      - "traefik.http.routers.backend.middlewares=backend-headers,backend-stripprefix"
      - "traefik.http.routers.backend.service=backend-service"
      - "traefik.http.services.backend-service.loadbalancer.server.port=1323"
      # Security Headers
      - "traefik.http.middlewares.backend-headers.headers.framedeny=true"
      - "traefik.http.middlewares.backend-headers.headers.browserxssfilter=true"
      # X-Content-Type-Options
      - "traefik.http.middlewares.backend-headers.headers.contentTypeNosniff=true"
      # Referrer-Policy
      - "traefik.http.middlewares.backend-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      # Access-Control Headers
      - "traefik.http.middlewares.backend-headers.headers.accesscontrolallowmethods=GET,POST,PATCH,DELETE"
      - "traefik.http.middlewares.backend-headers.headers.accesscontrolallowheaders=Content-Type"
      - "traefik.http.middlewares.backend-headers.headers.accesscontrolalloworiginlist=http://localhost"
      - "traefik.http.middlewares.backend-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.backend-headers.headers.addvaryheader=true"
      # CORS Headers
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.Cross-Origin-Opener-Policy=same-origin;"
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.Cross-Origin-Embedder-Policy=require-corp;"
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.Cross-Origin-Resource-Policy=same-site;"
      # Permissions-Policy
      - "traefik.http.middlewares.backend-headers.headers.permissionsPolicy=geolocation=(),camera=(),interest-cohort=()"
      # Custom Headers Hardening
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.expect-ct="
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.server="
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.x-powered-by="
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.x-dns-prefetch-control=off"
      - "traefik.http.middlewares.backend-headers.headers.customResponseHeaders.public-key-pins="

  frontend:
    image: kracker-frontend:local
    env_file:
      - front/.env.local
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && (!PathPrefix(`/back`))"
      - "traefik.http.routers.frontend.middlewares=frontend-headers"
      - "traefik.http.routers.frontend.service=frontend-service"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=3000"
      # Security Headers
      - "traefik.http.middlewares.frontend-headers.headers.framedeny=true"
      - "traefik.http.middlewares.frontend-headers.headers.browserxssfilter=true"
      # X-Content-Type-Options
      - "traefik.http.middlewares.frontend-headers.headers.contentTypeNosniff=true"
      # Referrer-Policy
      - "traefik.http.middlewares.frontend-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      # Access-Control Headers
      - "traefik.http.middlewares.frontend-headers.headers.accesscontrolallowmethods=GET,POST,PATCH,DELETE"
      - "traefik.http.middlewares.frontend-headers.headers.accesscontrolallowheaders=Content-Type"
      - "traefik.http.middlewares.frontend-headers.headers.accesscontrolalloworiginlist=http://localhost"
      - "traefik.http.middlewares.frontend-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.frontend-headers.headers.addvaryheader=true"
      # CORS Headers
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.Cross-Origin-Opener-Policy=same-origin;"
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.Cross-Origin-Embedder-Policy=require-corp;"
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.Cross-Origin-Resource-Policy=same-site;"
      # Permissions-Policy
      - "traefik.http.middlewares.frontend-headers.headers.permissionsPolicy=geolocation=(),camera=(),interest-cohort=()"
      # Custom Headers Hardening
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.expect-ct="
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.server="
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.x-powered-by="
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.x-dns-prefetch-control=off"
      - "traefik.http.middlewares.frontend-headers.headers.customResponseHeaders.public-key-pins="

      # Content-Security-Policy
      - "traefik.http.middlewares.frontend-headers.headers.contentSecurityPolicy=default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; frame-ancestors 'self'; form-action 'self';"

  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
        max-size: "10m"
    networks:
      - kracker

networks:
  kracker:
    driver: bridge
