services:
  web:
    build: .
    ports:
      - "1323:1323"
    networks:
      - kracker

  db:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: { { .Env.DB_USER } }
      POSTGRES_PASSWORD: { { .Env.DB_PASSWORD } }
      POSTGRES_DB: { { .Env.DB_NAME } }
    networks:
      - kracker

networks:
  kracker:
    driver: bridge
