version: "3.9"

services:
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - kracker

  web:
    image: kracker-back:local
    ports:
      - "1323:1323"
    depends_on:
      - db
    env_file:
      - .env.local
    networks:
      - kracker

networks:
  kracker:
    driver: bridge
