log:
  level: DEBUG # DEBUG for initial setup, recommended to change to INFO for production ready
  format: "json"

accessLog:
  format: "json"
  fields:
    defaultMode: keep

api: {}

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web-traefik:
    address: ":8085"
  web-secure:
    address: ":443"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

certificatesResolvers:
  letsencrypt:
    acme:
      email: "your@email.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
