// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    int64              `json:"user_id"`
}

type User struct {
	ID         int64  `json:"id"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	SaltedHash string `json:"salted_hash"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	IsAdmin    bool   `json:"is_admin"`
}
