name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --tls=false
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: back/go.sum

    - name: Install dependencies
      run: |
        cd back
        go mod tidy 

    - name: Run Go tests
      run: |
        cd back
        go run gotest.tools/gotestsum@latest --junitfile junit.xml -- -v -coverpkg=./... -coverprofile=profile.cov ./...
        go tool cover -func profile.cov
          
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: go-test-artifacts
        path: |
          back/junit.xml
          back/profile.cov
